#!/bin/sh
### BEGIN INIT INFO
# Provides:          obs
# Required-Start:    $local_fs $network $remote_fs $x11
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OBS service
# Description:       Starts the OBS service after X11
### END INIT INFO

case "$1" in
    start)
        echo "Starting obs..."
        obs --disable-shutdown-check --disable-updater  &
        ;;
    stop)
        echo "Stopping obs..."
        pkill -f obs
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        if pgrep -f obs > /dev/null; then
            echo "obs is running."
        else
            echo "obs is not running."
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/obs {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
